#!/usr/bin/env bash
set -euo pipefail

APP_NAME="ino-agent"
ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT_DIR"

if [[ "$(uname)" != "Darwin" ]]; then
  echo "This macOS build script must be run on macOS."
  exit 1
fi

source "$HOME/.cargo/env" 2>/dev/null || true

if ! command -v node >/dev/null 2>&1; then
  echo "Node.js is required. Install Node 20+."
  exit 1
fi

if ! command -v cargo >/dev/null 2>&1; then
  echo "Rust is required. Install via: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
  exit 1
fi

mkdir -p assets
if [[ -f "assets/new_logo.png" && ! -f "assets/logo.png" ]] || [[ "assets/new_logo.png" -nt "assets/logo.png" ]]; then
  cp assets/new_logo.png assets/logo.png
fi

if [[ ! -f "assets/logo.png" ]]; then
  echo "Missing assets/logo.png"
  exit 1
fi

python3 scripts/make_icon.py
# The DMG background (src-tauri/dmg/background.png) is a committed design asset
# generated by scripts/make_dmg_background.py; no need to regenerate it here.

npm install
# Tauri builds the .app (ad-hoc signed via bundle.macOS.signingIdentity) and a
# styled .dmg (background, window size, icon positions come from
# bundle.macOS.dmg in tauri.conf.json). The signature is NOT notarized, so users
# who download the DMG must still clear Gatekeeper once (right-click > Open, or
# `xattr -dr com.apple.quarantine /Applications/${APP_NAME}.app`).
npm run tauri build

APP_PATH="src-tauri/target/release/bundle/macos/${APP_NAME}.app"
if [[ ! -d "$APP_PATH" ]]; then
  APP_PATH=$(find src-tauri/target/release/bundle/macos -name "*.app" -type d | head -1)
fi

DMG_PATH=$(find src-tauri/target/release/bundle/dmg -name "*.dmg" -type f | head -1)
if [[ -z "$DMG_PATH" ]]; then
  echo "Tauri did not produce a .dmg in src-tauri/target/release/bundle/dmg"
  exit 1
fi

mkdir -p dist
rm -rf "dist/${APP_NAME}.app"
cp -R "$APP_PATH" "dist/${APP_NAME}.app"
cp -f "$DMG_PATH" "dist/${APP_NAME}-mac.dmg"

shasum -a 256 "dist/${APP_NAME}-mac.dmg" > "dist/${APP_NAME}-mac.dmg.sha256"

echo "Built: dist/${APP_NAME}.app"
echo "Built: dist/${APP_NAME}-mac.dmg"
echo "Checksum: dist/${APP_NAME}-mac.dmg.sha256"
