use serde::{Deserialize, Serialize};
use std::fs;
use std::io::Read;
use std::path::{Component, Path, PathBuf};
use std::process::{Command, Stdio};
use std::thread;
use std::time::{Duration, Instant};

const DEFAULT_TIMEOUT_MS: u64 = 20_000;
const RUN_TIMEOUT_MS: u64 = 8_000;
const MAX_TIMEOUT_MS: u64 = 60_000;
const MAX_OUTPUT_LENGTH: usize = 100_000;

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ProjectStackSummary {
    pub id: String,
    pub name: String,
    pub description: String,
    pub commands: Vec<ProjectCommandSpec>,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ProjectCommandSpec {
    pub kind: String,
    pub label: String,
    pub command: String,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreateProjectRequest {
    pub name: String,
    pub stack: String,
    pub path: Option<String>,
    pub description: Option<String>,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CreatedProject {
    pub name: String,
    pub stack: String,
    pub path: String,
    pub absolute_path: String,
    pub files: Vec<String>,
    pub commands: Vec<ProjectCommandSpec>,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RunProjectCommandRequest {
    pub path: String,
    pub stack: String,
    pub command_kind: String,
    pub timeout_ms: Option<u64>,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ProjectCommandResult {
    pub command: String,
    pub cwd: String,
    pub success: bool,
    pub stdout: String,
    pub stderr: String,
    pub exit_code: Option<i32>,
    pub duration_ms: u128,
    pub timed_out: bool,
    pub diagnosis: String,
}

#[derive(Debug, Clone, Copy)]
enum ProjectStack {
    PythonCli,
    PythonResearch,
    CppCmake,
    Rust,
    TypeScriptReact,
    TauriApp,
    StudyNotes,
    ResearchWorkspace,
}

#[derive(Debug)]
struct FileTemplate {
    path: &'static str,
    content: String,
}

#[derive(Debug)]
struct CommandStep {
    program: &'static str,
    args: &'static [&'static str],
}

pub fn list_project_stacks() -> Vec<ProjectStackSummary> {
    ProjectStack::all()
        .into_iter()
        .map(|stack| ProjectStackSummary {
            id: stack.id().to_string(),
            name: stack.name().to_string(),
            description: stack.description().to_string(),
            commands: stack.commands(),
        })
        .collect()
}

pub fn create_project(
    workspace_root: &Path,
    request: CreateProjectRequest,
) -> Result<CreatedProject, String> {
    let stack = ProjectStack::from_id(&request.stack)?;
    let name = normalize_project_name(&request.name)?;
    let relative_path = request
        .path
        .as_deref()
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .map(ToString::to_string)
        .unwrap_or_else(|| format!("projects/{name}"));
    let target = resolve_new_project_path(workspace_root, &relative_path)?;
    ensure_creatable_dir(&target)?;

    let description = request
        .description
        .as_deref()
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .unwrap_or("Generated by ino-agent project wizard.");
    let templates = stack.templates(&name, description);
    fs::create_dir_all(&target).map_err(|e| e.to_string())?;
    let mut files = Vec::new();

    for template in templates {
        let file_path = target.join(template.path);
        if let Some(parent) = file_path.parent() {
            fs::create_dir_all(parent).map_err(|e| e.to_string())?;
        }
        fs::write(&file_path, template.content).map_err(|e| e.to_string())?;
        files.push(template.path.to_string());
    }

    files.sort();
    Ok(CreatedProject {
        name,
        stack: stack.id().to_string(),
        path: display_workspace_path(workspace_root, &target),
        absolute_path: target.display().to_string(),
        files,
        commands: stack.commands(),
    })
}

pub fn run_project_command(
    workspace_root: &Path,
    request: RunProjectCommandRequest,
) -> Result<ProjectCommandResult, String> {
    let stack = ProjectStack::from_id(&request.stack)?;
    let cwd = resolve_existing_project_path(workspace_root, &request.path)?;
    let steps = stack.command_steps(&request.command_kind)?;
    let command_label = stack
        .commands()
        .into_iter()
        .find(|command| command.kind == request.command_kind)
        .map(|command| command.command)
        .unwrap_or_else(|| request.command_kind.clone());

    let timeout_ms = request
        .timeout_ms
        .unwrap_or_else(|| {
            if request.command_kind == "run" {
                RUN_TIMEOUT_MS
            } else {
                DEFAULT_TIMEOUT_MS
            }
        })
        .clamp(1, MAX_TIMEOUT_MS);
    let started = Instant::now();
    let mut stdout = String::new();
    let mut stderr = String::new();
    let mut exit_code = Some(0);
    let mut timed_out = false;

    for step in steps {
        let remaining = timeout_ms.saturating_sub(started.elapsed().as_millis() as u64);
        if remaining == 0 {
            timed_out = true;
            exit_code = None;
            break;
        }
        let result = execute_step(&step, &cwd, remaining)?;
        append_step_output(&mut stdout, "$ ");
        append_step_output(&mut stdout, step.program);
        for arg in step.args {
            append_step_output(&mut stdout, " ");
            append_step_output(&mut stdout, arg);
        }
        append_step_output(&mut stdout, "\n");
        append_step_output(&mut stdout, &result.stdout);
        append_step_output(&mut stderr, &result.stderr);
        exit_code = result.exit_code;
        timed_out = result.timed_out;
        if !result.success {
            let diagnosis =
                diagnose_failure(stack, &request.command_kind, &stdout, &stderr, timed_out);
            return Ok(ProjectCommandResult {
                command: command_label,
                cwd: display_workspace_path(workspace_root, &cwd),
                success: false,
                stdout,
                stderr,
                exit_code,
                duration_ms: started.elapsed().as_millis(),
                timed_out,
                diagnosis,
            });
        }
    }

    let diagnosis = diagnose_failure(stack, &request.command_kind, &stdout, &stderr, timed_out);
    Ok(ProjectCommandResult {
        command: command_label,
        cwd: display_workspace_path(workspace_root, &cwd),
        success: !timed_out && exit_code == Some(0),
        stdout,
        stderr,
        exit_code,
        duration_ms: started.elapsed().as_millis(),
        timed_out,
        diagnosis,
    })
}

impl ProjectStack {
    fn all() -> Vec<Self> {
        vec![
            Self::PythonCli,
            Self::PythonResearch,
            Self::CppCmake,
            Self::Rust,
            Self::TypeScriptReact,
            Self::TauriApp,
            Self::StudyNotes,
            Self::ResearchWorkspace,
        ]
    }

    fn from_id(id: &str) -> Result<Self, String> {
        match id {
            "python_cli" => Ok(Self::PythonCli),
            "python_research" => Ok(Self::PythonResearch),
            "cpp_cmake" => Ok(Self::CppCmake),
            "rust" => Ok(Self::Rust),
            "typescript_react" => Ok(Self::TypeScriptReact),
            "tauri_app" => Ok(Self::TauriApp),
            "study_notes" => Ok(Self::StudyNotes),
            "research_workspace" => Ok(Self::ResearchWorkspace),
            other => Err(format!("Unsupported project stack: {other}")),
        }
    }

    fn id(self) -> &'static str {
        match self {
            Self::PythonCli => "python_cli",
            Self::PythonResearch => "python_research",
            Self::CppCmake => "cpp_cmake",
            Self::Rust => "rust",
            Self::TypeScriptReact => "typescript_react",
            Self::TauriApp => "tauri_app",
            Self::StudyNotes => "study_notes",
            Self::ResearchWorkspace => "research_workspace",
        }
    }

    fn name(self) -> &'static str {
        match self {
            Self::PythonCli => "Python CLI",
            Self::PythonResearch => "Python notebook/research",
            Self::CppCmake => "C++/CMake",
            Self::Rust => "Rust",
            Self::TypeScriptReact => "TypeScript/React",
            Self::TauriApp => "Tauri app",
            Self::StudyNotes => "Учебный конспект",
            Self::ResearchWorkspace => "Research workspace",
        }
    }

    fn description(self) -> &'static str {
        match self {
            Self::PythonCli => "Small command-line app with unittest smoke coverage.",
            Self::PythonResearch => "Research notes, scripts, sample data and reproducible checks.",
            Self::CppCmake => "CMake project with a library target, executable and CTest test.",
            Self::Rust => "Cargo binary crate with a starter test.",
            Self::TypeScriptReact => "Vite React app with TypeScript and a minimal component.",
            Self::TauriApp => "Minimal Tauri 2 desktop app scaffold.",
            Self::StudyNotes => "Markdown course workspace with topic map and review plan.",
            Self::ResearchWorkspace => {
                "Experiment log, sources, data folders and reproducibility script."
            }
        }
    }

    fn commands(self) -> Vec<ProjectCommandSpec> {
        match self {
            Self::PythonCli => vec![
                command("build", "Build", "python3 -m py_compile src/main.py"),
                command("run", "Run", "python3 src/main.py"),
                command("test", "Test", "python3 -m unittest discover -s tests"),
            ],
            Self::PythonResearch => vec![
                command(
                    "build",
                    "Build",
                    "python3 -m py_compile scripts/check_workspace.py",
                ),
                command("run", "Run", "python3 notebooks/smoke.py"),
                command("test", "Test", "python3 -m unittest discover -s tests"),
            ],
            Self::CppCmake => vec![
                command(
                    "build",
                    "Build",
                    "cmake -S . -B build && cmake --build build",
                ),
                command("run", "Run", "./build/app"),
                command("test", "Test", "ctest --test-dir build --output-on-failure"),
            ],
            Self::Rust => vec![
                command("build", "Build", "cargo build"),
                command("run", "Run", "cargo run"),
                command("test", "Test", "cargo test"),
            ],
            Self::TypeScriptReact => vec![
                command("build", "Build", "npm run build"),
                command("run", "Run", "npm run dev"),
                command("test", "Test", "npm run typecheck"),
            ],
            Self::TauriApp => vec![
                command("build", "Build", "npm run build"),
                command("run", "Run", "npm run tauri:dev"),
                command("test", "Test", "npm run typecheck"),
            ],
            Self::StudyNotes | Self::ResearchWorkspace => vec![
                command("build", "Build", "python3 scripts/check_workspace.py"),
                command("run", "Run", "python3 scripts/summary.py"),
                command("test", "Test", "python3 scripts/check_workspace.py"),
            ],
        }
    }

    fn command_steps(self, kind: &str) -> Result<Vec<CommandStep>, String> {
        let steps = match (self, kind) {
            (Self::PythonCli, "build") => {
                vec![step("python3", &["-m", "py_compile", "src/main.py"])]
            }
            (Self::PythonCli, "run") => vec![step("python3", &["src/main.py"])],
            (Self::PythonCli, "test") => vec![step(
                "python3",
                &["-m", "unittest", "discover", "-s", "tests"],
            )],
            (Self::PythonResearch, "build") => vec![step(
                "python3",
                &["-m", "py_compile", "scripts/check_workspace.py"],
            )],
            (Self::PythonResearch, "run") => vec![step("python3", &["notebooks/smoke.py"])],
            (Self::PythonResearch, "test") => vec![step(
                "python3",
                &["-m", "unittest", "discover", "-s", "tests"],
            )],
            (Self::CppCmake, "build") => vec![
                step("cmake", &["-S", ".", "-B", "build"]),
                step("cmake", &["--build", "build"]),
            ],
            (Self::CppCmake, "run") => vec![step("./build/app", &[])],
            (Self::CppCmake, "test") => vec![step(
                "ctest",
                &["--test-dir", "build", "--output-on-failure"],
            )],
            (Self::Rust, "build") => vec![step("cargo", &["build"])],
            (Self::Rust, "run") => vec![step("cargo", &["run"])],
            (Self::Rust, "test") => vec![step("cargo", &["test"])],
            (Self::TypeScriptReact, "build") => vec![step("npm", &["run", "build"])],
            (Self::TypeScriptReact, "run") => vec![step("npm", &["run", "dev"])],
            (Self::TypeScriptReact, "test") => vec![step("npm", &["run", "typecheck"])],
            (Self::TauriApp, "build") => vec![step("npm", &["run", "build"])],
            (Self::TauriApp, "run") => vec![step("npm", &["run", "tauri:dev"])],
            (Self::TauriApp, "test") => vec![step("npm", &["run", "typecheck"])],
            (Self::StudyNotes, "build" | "test") => {
                vec![step("python3", &["scripts/check_workspace.py"])]
            }
            (Self::StudyNotes, "run") => vec![step("python3", &["scripts/summary.py"])],
            (Self::ResearchWorkspace, "build" | "test") => {
                vec![step("python3", &["scripts/check_workspace.py"])]
            }
            (Self::ResearchWorkspace, "run") => vec![step("python3", &["scripts/summary.py"])],
            _ => {
                return Err(format!(
                    "Unsupported command kind for {}: {kind}",
                    self.id()
                ))
            }
        };
        Ok(steps)
    }

    fn templates(self, name: &str, description: &str) -> Vec<FileTemplate> {
        match self {
            Self::PythonCli => python_cli_templates(name, description),
            Self::PythonResearch => python_research_templates(name, description),
            Self::CppCmake => cpp_cmake_templates(name, description),
            Self::Rust => rust_templates(name, description),
            Self::TypeScriptReact => typescript_react_templates(name, description),
            Self::TauriApp => tauri_templates(name, description),
            Self::StudyNotes => study_notes_templates(name, description),
            Self::ResearchWorkspace => research_workspace_templates(name, description),
        }
    }
}

fn command(kind: &str, label: &str, command: &str) -> ProjectCommandSpec {
    ProjectCommandSpec {
        kind: kind.to_string(),
        label: label.to_string(),
        command: command.to_string(),
    }
}

fn step(program: &'static str, args: &'static [&'static str]) -> CommandStep {
    CommandStep { program, args }
}

fn normalize_project_name(value: &str) -> Result<String, String> {
    let mut name = value.trim().to_lowercase();
    name = name
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '-' || ch == '_' {
                ch
            } else if ch.is_whitespace() {
                '-'
            } else {
                '-'
            }
        })
        .collect::<String>();
    while name.contains("--") {
        name = name.replace("--", "-");
    }
    name = name.trim_matches('-').to_string();
    if name.is_empty() {
        return Err("Project name is required.".to_string());
    }
    if name.len() > 80 {
        return Err("Project name is too long. Max length: 80.".to_string());
    }
    Ok(name)
}

fn resolve_new_project_path(workspace_root: &Path, relative_path: &str) -> Result<PathBuf, String> {
    let path = normalize_relative_path(relative_path)?;
    Ok(workspace_root.join(path))
}

fn resolve_existing_project_path(workspace_root: &Path, path: &str) -> Result<PathBuf, String> {
    let path = normalize_relative_path(path)?;
    let full = workspace_root.join(path);
    if !full.is_dir() {
        return Err("Project directory does not exist.".to_string());
    }
    Ok(full)
}

fn normalize_relative_path(path: &str) -> Result<PathBuf, String> {
    let path = Path::new(path.trim());
    if path.as_os_str().is_empty() {
        return Err("Project path is required.".to_string());
    }
    if path.is_absolute() {
        return Err("Project path must be relative to the workspace.".to_string());
    }
    let mut normalized = PathBuf::new();
    for component in path.components() {
        match component {
            Component::Normal(part) => normalized.push(part),
            Component::CurDir => {}
            _ => return Err("Project path cannot contain parent directory segments.".to_string()),
        }
    }
    if normalized.as_os_str().is_empty() {
        return Err("Project path is required.".to_string());
    }
    Ok(normalized)
}

fn ensure_creatable_dir(path: &Path) -> Result<(), String> {
    if path.exists() && !path.is_dir() {
        return Err("Target path exists and is not a directory.".to_string());
    }
    if path.is_dir() {
        let mut entries = fs::read_dir(path).map_err(|e| e.to_string())?;
        if entries.next().is_some() {
            return Err("Target directory is not empty. Choose another path.".to_string());
        }
    }
    Ok(())
}

fn display_workspace_path(workspace_root: &Path, path: &Path) -> String {
    path.strip_prefix(workspace_root)
        .unwrap_or(path)
        .to_string_lossy()
        .trim_start_matches('/')
        .to_string()
}

fn execute_step(
    step: &CommandStep,
    cwd: &Path,
    timeout_ms: u64,
) -> Result<ProjectCommandResult, String> {
    let started = Instant::now();
    let mut child = Command::new(step.program)
        .args(step.args)
        .current_dir(cwd)
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| format!("Failed to start {}: {e}", step.program))?;

    let stdout = child
        .stdout
        .take()
        .ok_or_else(|| "Failed to capture stdout.".to_string())?;
    let stderr = child
        .stderr
        .take()
        .ok_or_else(|| "Failed to capture stderr.".to_string())?;
    let stdout_handle = thread::spawn(move || read_limited(stdout));
    let stderr_handle = thread::spawn(move || read_limited(stderr));
    let timeout = Duration::from_millis(timeout_ms);
    let (exit_code, timed_out) = loop {
        if let Some(status) = child.try_wait().map_err(|e| e.to_string())? {
            break (status.code(), false);
        }
        if started.elapsed() >= timeout {
            let _ = child.kill();
            let _ = child.wait();
            break (None, true);
        }
        thread::sleep(Duration::from_millis(20));
    };
    let stdout = stdout_handle.join().unwrap_or_default();
    let stderr = stderr_handle.join().unwrap_or_default();
    let success = !timed_out && exit_code == Some(0);
    Ok(ProjectCommandResult {
        command: format!("{} {}", step.program, step.args.join(" "))
            .trim()
            .to_string(),
        cwd: cwd.display().to_string(),
        success,
        stdout,
        stderr,
        exit_code,
        duration_ms: started.elapsed().as_millis(),
        timed_out,
        diagnosis: String::new(),
    })
}

fn read_limited(mut reader: impl Read) -> String {
    let mut output = Vec::new();
    let mut buffer = [0_u8; 8192];
    let mut truncated = false;
    loop {
        let Ok(read) = reader.read(&mut buffer) else {
            break;
        };
        if read == 0 {
            break;
        }
        let remaining = MAX_OUTPUT_LENGTH.saturating_sub(output.len());
        if remaining == 0 {
            truncated = true;
            continue;
        }
        let take = remaining.min(read);
        output.extend_from_slice(&buffer[..take]);
        if take < read {
            truncated = true;
        }
    }
    let mut text = String::from_utf8_lossy(&output).to_string();
    if truncated {
        text.push_str("\n[output truncated]");
    }
    text
}

fn append_step_output(target: &mut String, value: &str) {
    if target.len() >= MAX_OUTPUT_LENGTH {
        return;
    }
    let remaining = MAX_OUTPUT_LENGTH - target.len();
    if value.len() <= remaining {
        target.push_str(value);
    } else {
        target.push_str(&value[..remaining]);
        target.push_str("\n[output truncated]");
    }
}

fn diagnose_failure(
    stack: ProjectStack,
    kind: &str,
    stdout: &str,
    stderr: &str,
    timed_out: bool,
) -> String {
    if timed_out {
        return "Command timed out. For dev servers this usually means the server started and kept running; stop it manually if needed.".to_string();
    }
    let combined = format!("{}\n{}", stdout.to_lowercase(), stderr.to_lowercase());
    if combined.contains("command not found") || combined.contains("no such file or directory") {
        return match stack {
            ProjectStack::PythonCli | ProjectStack::PythonResearch | ProjectStack::StudyNotes | ProjectStack::ResearchWorkspace => {
                "Required runtime is missing or not on PATH. Install Python 3 and retry.".to_string()
            }
            ProjectStack::CppCmake => {
                "Required C++ toolchain or CMake is missing. Install CMake and a compiler, then retry.".to_string()
            }
            ProjectStack::Rust => {
                "Cargo is missing or not on PATH. Install Rust toolchain, then retry.".to_string()
            }
            ProjectStack::TypeScriptReact | ProjectStack::TauriApp => {
                "Node/npm dependencies may be missing. Run npm install in the project folder, then retry.".to_string()
            }
        };
    }
    if combined.contains("cannot find module") || combined.contains("vite: not found") {
        return "Node dependencies are missing. Run npm install in the project folder, then retry."
            .to_string();
    }
    if matches!(stack, ProjectStack::CppCmake)
        && kind != "build"
        && combined.contains("no tests were found")
    {
        return "Build the CMake project before running tests.".to_string();
    }
    if combined.contains("failed") || combined.contains("error") {
        return "Command failed. Check stderr above; the next agent step should inspect the failing file and propose a repair.".to_string();
    }
    String::new()
}

fn python_cli_templates(name: &str, description: &str) -> Vec<FileTemplate> {
    vec![
        file("README.md", format!("# {name}\n\n{description}\n\n## Commands\n\n```bash\npython3 -m py_compile src/main.py\npython3 src/main.py\npython3 -m unittest discover -s tests\n```\n")),
        file(".gitignore", "__pycache__/\n*.py[cod]\n.venv/\n.env\n.DS_Store\n".to_string()),
        file("src/main.py", "def greet(name: str = \"student\") -> str:\n    return f\"Hello, {name}!\"\n\n\nif __name__ == \"__main__\":\n    print(greet())\n".to_string()),
        file("tests/test_main.py", "import unittest\nfrom src.main import greet\n\n\nclass MainTest(unittest.TestCase):\n    def test_greet(self):\n        self.assertEqual(greet(\"ino\"), \"Hello, ino!\")\n\n\nif __name__ == \"__main__\":\n    unittest.main()\n".to_string()),
    ]
}

fn python_research_templates(name: &str, description: &str) -> Vec<FileTemplate> {
    vec![
        file("README.md", format!("# {name}\n\n{description}\n\n## Layout\n\n- `data/raw` for original data.\n- `data/processed` for derived artifacts.\n- `notebooks` for experiments.\n- `scripts` for repeatable checks.\n\n## Commands\n\n```bash\npython3 notebooks/smoke.py\npython3 -m unittest discover -s tests\n```\n")),
        file(".gitignore", "__pycache__/\n*.py[cod]\n.venv/\n.env\n.DS_Store\ndata/raw/*\n!data/raw/.gitkeep\ndata/processed/*\n!data/processed/.gitkeep\n".to_string()),
        file("data/raw/.gitkeep", String::new()),
        file("data/processed/.gitkeep", String::new()),
        file("notebooks/smoke.py", "from pathlib import Path\n\nROOT = Path(__file__).resolve().parents[1]\nprint(f\"Research workspace: {ROOT.name}\")\n".to_string()),
        file("scripts/check_workspace.py", "from pathlib import Path\n\nrequired = [\"README.md\", \"data/raw\", \"data/processed\", \"notebooks\"]\nmissing = [item for item in required if not (Path.cwd() / item).exists()]\nif missing:\n    raise SystemExit(f\"Missing required paths: {', '.join(missing)}\")\nprint(\"Workspace check passed\")\n".to_string()),
        file("tests/test_workspace.py", "import unittest\nfrom pathlib import Path\n\n\nclass WorkspaceTest(unittest.TestCase):\n    def test_readme_exists(self):\n        self.assertTrue((Path.cwd() / \"README.md\").exists())\n\n\nif __name__ == \"__main__\":\n    unittest.main()\n".to_string()),
    ]
}

fn cpp_cmake_templates(name: &str, description: &str) -> Vec<FileTemplate> {
    vec![
        file("README.md", format!("# {name}\n\n{description}\n\n## Commands\n\n```bash\ncmake -S . -B build\ncmake --build build\nctest --test-dir build --output-on-failure\n```\n")),
        file(".gitignore", "build/\n.DS_Store\n".to_string()),
        file("CMakeLists.txt", "cmake_minimum_required(VERSION 3.20)\nproject(starter_app LANGUAGES CXX)\n\nset(CMAKE_CXX_STANDARD 20)\nset(CMAKE_CXX_STANDARD_REQUIRED ON)\n\nenable_testing()\n\nadd_library(core src/lib.cpp)\ntarget_include_directories(core PUBLIC include)\n\nadd_executable(app src/main.cpp)\ntarget_link_libraries(app PRIVATE core)\n\nadd_executable(core_test tests/core_test.cpp)\ntarget_link_libraries(core_test PRIVATE core)\nadd_test(NAME core_test COMMAND core_test)\n".to_string()),
        file("include/core.hpp", "#pragma once\n\nint answer();\n".to_string()),
        file("src/lib.cpp", "#include \"core.hpp\"\n\nint answer() {\n    return 42;\n}\n".to_string()),
        file("src/main.cpp", "#include <iostream>\n#include \"core.hpp\"\n\nint main() {\n    std::cout << \"Answer: \" << answer() << '\\n';\n    return 0;\n}\n".to_string()),
        file("tests/core_test.cpp", "#include \"core.hpp\"\n\nint main() {\n    return answer() == 42 ? 0 : 1;\n}\n".to_string()),
    ]
}

fn rust_templates(name: &str, description: &str) -> Vec<FileTemplate> {
    vec![
        file("README.md", format!("# {name}\n\n{description}\n\n## Commands\n\n```bash\ncargo build\ncargo run\ncargo test\n```\n")),
        file(".gitignore", "target/\n.DS_Store\n".to_string()),
        file("Cargo.toml", format!("[package]\nname = \"{}\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dependencies]\n", name.replace('-', "_"))),
        file("src/main.rs", "fn answer() -> i32 {\n    42\n}\n\nfn main() {\n    println!(\"Answer: {}\", answer());\n}\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n\n    #[test]\n    fn answer_is_stable() {\n        assert_eq!(answer(), 42);\n    }\n}\n".to_string()),
    ]
}

fn typescript_react_templates(name: &str, description: &str) -> Vec<FileTemplate> {
    vec![
        file("README.md", format!("# {name}\n\n{description}\n\n## Commands\n\n```bash\nnpm install\nnpm run dev\nnpm run build\nnpm run typecheck\n```\n")),
        file(".gitignore", "node_modules/\ndist/\n.env\n.DS_Store\n".to_string()),
        file("package.json", format!("{{\n  \"name\": \"{name}\",\n  \"private\": true,\n  \"version\": \"0.1.0\",\n  \"type\": \"module\",\n  \"scripts\": {{\n    \"dev\": \"vite\",\n    \"build\": \"tsc && vite build\",\n    \"typecheck\": \"tsc --noEmit\"\n  }},\n  \"dependencies\": {{\n    \"@vitejs/plugin-react\": \"^4.4.1\",\n    \"vite\": \"^6.3.5\",\n    \"typescript\": \"^5.8.3\",\n    \"react\": \"^18.3.1\",\n    \"react-dom\": \"^18.3.1\"\n  }},\n  \"devDependencies\": {{\n    \"@types/react\": \"^18.3.20\",\n    \"@types/react-dom\": \"^18.3.6\"\n  }}\n}}\n")),
        file("index.html", "<!doctype html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"UTF-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n    <title>Starter App</title>\n  </head>\n  <body>\n    <div id=\"root\"></div>\n    <script type=\"module\" src=\"/src/main.tsx\"></script>\n  </body>\n</html>\n".to_string()),
        file("tsconfig.json", "{\n  \"compilerOptions\": {\n    \"target\": \"ES2020\",\n    \"useDefineForClassFields\": true,\n    \"lib\": [\"DOM\", \"DOM.Iterable\", \"ES2020\"],\n    \"allowJs\": false,\n    \"skipLibCheck\": true,\n    \"esModuleInterop\": true,\n    \"allowSyntheticDefaultImports\": true,\n    \"strict\": true,\n    \"forceConsistentCasingInFileNames\": true,\n    \"module\": \"ESNext\",\n    \"moduleResolution\": \"Node\",\n    \"resolveJsonModule\": true,\n    \"isolatedModules\": true,\n    \"noEmit\": true,\n    \"jsx\": \"react-jsx\"\n  },\n  \"include\": [\"src\"]\n}\n".to_string()),
        file("src/main.tsx", "import React from \"react\";\nimport { createRoot } from \"react-dom/client\";\nimport \"./style.css\";\n\nfunction App() {\n  return <main className=\"app\"><h1>Starter App</h1><p>Build something useful.</p></main>;\n}\n\ncreateRoot(document.getElementById(\"root\")!).render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>,\n);\n".to_string()),
        file("src/style.css", "body {\n  margin: 0;\n  font-family: Inter, ui-sans-serif, system-ui, sans-serif;\n  background: #f7f7f5;\n  color: #1d1d1f;\n}\n\n.app {\n  min-height: 100vh;\n  display: grid;\n  place-content: center;\n  gap: 8px;\n  text-align: center;\n}\n".to_string()),
    ]
}

fn tauri_templates(name: &str, description: &str) -> Vec<FileTemplate> {
    let mut files = typescript_react_templates(name, description);
    if let Some(package_json) = files.iter_mut().find(|file| file.path == "package.json") {
        package_json.content = format!("{{\n  \"name\": \"{name}\",\n  \"private\": true,\n  \"version\": \"0.1.0\",\n  \"type\": \"module\",\n  \"scripts\": {{\n    \"dev\": \"vite --host 127.0.0.1 --port 1420\",\n    \"build\": \"tsc && vite build\",\n    \"typecheck\": \"tsc --noEmit\",\n    \"tauri:dev\": \"tauri dev\",\n    \"tauri:build\": \"tauri build\"\n  }},\n  \"dependencies\": {{\n    \"@tauri-apps/api\": \"^2.5.0\",\n    \"@vitejs/plugin-react\": \"^4.4.1\",\n    \"vite\": \"^6.3.5\",\n    \"typescript\": \"^5.8.3\",\n    \"react\": \"^18.3.1\",\n    \"react-dom\": \"^18.3.1\"\n  }},\n  \"devDependencies\": {{\n    \"@tauri-apps/cli\": \"^2.5.0\",\n    \"@types/react\": \"^18.3.20\",\n    \"@types/react-dom\": \"^18.3.6\"\n  }}\n}}\n");
    }
    files.push(file("src-tauri/Cargo.toml", format!("[package]\nname = \"{}\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[build-dependencies]\ntauri-build = {{ version = \"2\", features = [] }}\n\n[dependencies]\ntauri = {{ version = \"2\", features = [] }}\nserde = {{ version = \"1\", features = [\"derive\"] }}\nserde_json = \"1\"\n\n[lib]\nname = \"{}_lib\"\ncrate-type = [\"lib\", \"cdylib\", \"staticlib\"]\n", name.replace('-', "_"), name.replace('-', "_"))));
    files.push(file(
        "src-tauri/build.rs",
        "fn main() {\n    tauri_build::build()\n}\n".to_string(),
    ));
    files.push(file("src-tauri/src/main.rs", "fn main() {\n    tauri::Builder::default()\n        .run(tauri::generate_context!())\n        .expect(\"error while running tauri application\");\n}\n".to_string()));
    files.push(file("src-tauri/tauri.conf.json", format!("{{\n  \"$schema\": \"https://schema.tauri.app/config/2\",\n  \"productName\": \"{name}\",\n  \"version\": \"0.1.0\",\n  \"identifier\": \"dev.ino.{name}\",\n  \"build\": {{\n    \"beforeDevCommand\": \"npm run dev\",\n    \"devUrl\": \"http://localhost:1420\",\n    \"beforeBuildCommand\": \"npm run build\",\n    \"frontendDist\": \"../dist\"\n  }},\n  \"app\": {{\n    \"windows\": [{{\n      \"title\": \"{name}\",\n      \"width\": 1000,\n      \"height\": 700\n    }}]\n  }},\n  \"bundle\": {{\n    \"active\": true,\n    \"targets\": \"all\"\n  }}\n}}\n")));
    files
}

fn study_notes_templates(name: &str, description: &str) -> Vec<FileTemplate> {
    vec![
        file("README.md", format!("# {name}\n\n{description}\n\n## Structure\n\n- `topics/` holds lesson notes.\n- `tasks/` holds practice tasks.\n- `review.md` tracks spaced review manually until the app owns it.\n")),
        file(".gitignore", ".DS_Store\n".to_string()),
        file("course_map.md", "# Course map\n\n- [ ] Topic 1\n- [ ] Topic 2\n- [ ] Topic 3\n".to_string()),
        file("topics/01-intro.md", "# Topic 1\n\n## Key ideas\n\n## Examples\n\n## Open questions\n".to_string()),
        file("tasks/01-practice.md", "# Practice 1\n\n1. Write the definition in your own words.\n2. Solve one small example.\n".to_string()),
        file("review.md", "# Review\n\n| Date | Topic | Result | Next review |\n| --- | --- | --- | --- |\n".to_string()),
        file("scripts/check_workspace.py", "from pathlib import Path\n\nrequired = [\"README.md\", \"course_map.md\", \"topics\", \"tasks\", \"review.md\"]\nmissing = [item for item in required if not (Path.cwd() / item).exists()]\nif missing:\n    raise SystemExit(f\"Missing required paths: {', '.join(missing)}\")\nprint(\"Study workspace check passed\")\n".to_string()),
        file("scripts/summary.py", "from pathlib import Path\n\nfor path in sorted(Path(\"topics\").glob(\"*.md\")):\n    print(f\"- {path.stem}: {path}\")\n".to_string()),
    ]
}

fn research_workspace_templates(name: &str, description: &str) -> Vec<FileTemplate> {
    vec![
        file("README.md", format!("# {name}\n\n{description}\n\n## Research question\n\nWrite the current question here.\n\n## Reproducibility\n\n```bash\npython3 scripts/check_workspace.py\npython3 scripts/summary.py\n```\n")),
        file(".gitignore", ".DS_Store\n.env\ndata/raw/*\n!data/raw/.gitkeep\ndata/processed/*\n!data/processed/.gitkeep\n".to_string()),
        file("sources.md", "# Sources\n\n| Source | Why it matters | Notes |\n| --- | --- | --- |\n".to_string()),
        file("experiments/001-baseline.md", "# Experiment 001: baseline\n\n## Hypothesis\n\n## Method\n\n## Result\n\n## Next step\n".to_string()),
        file("data/raw/.gitkeep", String::new()),
        file("data/processed/.gitkeep", String::new()),
        file("scripts/check_workspace.py", "from pathlib import Path\n\nrequired = [\"README.md\", \"sources.md\", \"experiments\", \"data/raw\", \"data/processed\"]\nmissing = [item for item in required if not (Path.cwd() / item).exists()]\nif missing:\n    raise SystemExit(f\"Missing required paths: {', '.join(missing)}\")\nprint(\"Research workspace check passed\")\n".to_string()),
        file("scripts/summary.py", "from pathlib import Path\n\nprint(\"Experiments:\")\nfor path in sorted(Path(\"experiments\").glob(\"*.md\")):\n    print(f\"- {path.stem}: {path}\")\n".to_string()),
    ]
}

fn file(path: &'static str, content: String) -> FileTemplate {
    FileTemplate { path, content }
}
